language: generic

env:
  - R_LIBS_USER=~/R

addons:
  apt:
    sources:
      - sourceline: 'deb https://cran.rstudio.com/bin/linux/ubuntu trusty/'
    packages:
      - r-base

install:
  - mkdir -p ~/R && Rscript -e 'install.packages(c("testthat", "covr"))'

script:
  - cd r && R CMD check .

after_success:
  - cd r && Rscript -e 'covr::codecov()'
